
  CREATE OR REPLACE EDITIONABLE PROCEDURE "MSSQL"."PROC_WRITEEXCEPTIONLOG" 
(
  IN_LOGNEXCEPT IN NUMBER
, IN_UNITID IN NUMBER
, IN_ASSIGNID IN NUMBER 
, IN_DESCID IN NUMBER 
, IN_DISCOUNTTYPE IN VARCHAR2 
, IN_DISCOUNTVALUE IN NUMBER
, IN_APPLIEDON IN VARCHAR2

, IN_INITIALVALUE IN NUMBER
, IN_EXCEPTVALUE IN NUMBER 
) AS 
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  insert into new_pricenexceptlog (LOGNEXCEPT,UNITID,ASSIGNID,DESCID,DISCOUNTTYPE,DISCOUNTVALUE,APPLIEDON,INITIALVALUE,EXCEPTVALUE)
  values
  (IN_LOGNEXCEPT,IN_UNITID,IN_ASSIGNID,IN_DESCID,IN_DISCOUNTTYPE,IN_DISCOUNTVALUE,IN_APPLIEDON,IN_INITIALVALUE,IN_EXCEPTVALUE);

  COMMIT;
END PROC_WRITEEXCEPTIONLOG;