
  CREATE TABLE "MSSQL"."PRICING" 
   (	"LISTPRICEID" NUMBER NOT NULL ENABLE, 
	"SERIES" VARCHAR2(200), 
	"MODEL" VARCHAR2(200), 
	"PLANT" NUMBER, 
	"BRAND" VARCHAR2(16), 
	"ACCOUNTID" VARCHAR2(200), 
	"OPTIONID" NUMBER NOT NULL ENABLE, 
	"PRICINGGROUPID" NUMBER NOT NULL ENABLE, 
	"CONSTRUCTIONCODE" CHAR(1), 
	"ORDERINDEX" NUMBER, 
	"STYLE" VARCHAR2(200), 
	"REC_CREATE_DATE" DATE, 
	"REC_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"UPDATED_BY" VARCHAR2(20), 
	"GROUPNAME" VARCHAR2(200), 
	"CUSTOMERID" VARCHAR2(40), 
	"CATEGORY" VARCHAR2(40), 
	"DATEEFFECTIVE" DATE, 
	 CONSTRAINT "UK_PRICING_RULE" UNIQUE ("SERIES", "MODEL", "PLANT", "BRAND", "ACCOUNTID", "OPTIONID", "PRICINGGROUPID", "CONSTRUCTIONCODE", "STYLE", "GROUPNAME", "CUSTOMERID", "CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "PK_PRICING" PRIMARY KEY ("LISTPRICEID")
  USING INDEX PCTFREE 3 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 131072 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 
