
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."BI_PRICING_GROUP_TRG" 
BEFORE INSERT ON PRICING_GROUP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRICING_GROUP_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
 ALTER TRIGGER "MSSQL"."BI_PRICING_GROUP_TRG" ENABLE
