
  CREATE TABLE "MSSQL"."PRICING_GROUP" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(200) NOT NULL ENABLE, 
	"ACCOUNTID" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATEDATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"USR" VARCHAR2(20), 
	"BATCH" VARCHAR2(20), 
	 CONSTRAINT "UK_PRICINGGROUPNAME_ACCTID" UNIQUE ("GROUPNAME", "ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "PRICING_GROUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "PRICING_GROUP_FK1" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES "MSSQL"."ACCOUNTSMASTER" ("ACCOUNTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 
