
  CREATE TABLE "MSSQL"."PRICINGSIZE" 
   (	"PRICINGSIZEID" NUMBER NOT NULL ENABLE, 
	"PRICINGSIZEGROUPID" NUMBER NOT NULL ENABLE, 
	"WIDTH" VARCHAR2(8) NOT NULL ENABLE, 
	"HEIGHT" VARCHAR2(8) NOT NULL ENABLE, 
	"SIZINGSYSTEM" CHAR(1) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,2) NOT NULL ENABLE, 
	"REC_CREATE_DATE" DATE NOT NULL ENABLE, 
	"REC_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"UPDATED_BY" VARCHAR2(20), 
	 CONSTRAINT "UK_W_H_PRICE" UNIQUE ("PRICINGSIZEGROUPID", "WIDTH", "HEIGHT", "SIZINGSYSTEM", "PRICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "PK_PRICINGSIZE" PRIMARY KEY ("PRICINGSIZEID")
  USING INDEX PCTFREE 3 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 131072 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 
