
  CREATE TABLE "MSSQL"."NEW_EXCEPTIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNTID" VARCHAR2(20) DEFAULT '0', 
	"SERIES" VARCHAR2(200) DEFAULT '0', 
	"MODEL" VARCHAR2(200) DEFAULT '0', 
	"EXCEPTIONDESC" NUMBER DEFAULT 0, 
	"DISCOUNTTYPE" VARCHAR2(100), 
	"DISCOUNTVALUE" NUMBER DEFAULT 0, 
	"STYLE" VARCHAR2(200) DEFAULT '0', 
	"CUSTOMERID" VARCHAR2(200) DEFAULT '0', 
	"EX_APPLYON" VARCHAR2(50), 
	"USER_ID" VARCHAR2(20), 
	"DATESTAMP" TIMESTAMP (6) DEFAULT sysdate, 
	 CONSTRAINT "EXCEPTIONASSIGNMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "NEW_EXCEPTIONS_APPLYON" UNIQUE ("ACCOUNTID", "SERIES", "MODEL", "STYLE", "EX_APPLYON", "EXCEPTIONDESC", "DISCOUNTTYPE", "DISCOUNTVALUE", "CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "NEW_EXCEPTIONS_FK1" FOREIGN KEY ("EXCEPTIONDESC")
	  REFERENCES "MSSQL"."NEW_EXCEPTIONDESC" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 