
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_EXCEPTIONS_TRG" 
BEFORE INSERT ON NEW_EXCEPTIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NEW_EXCEPTIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

