
  CREATE TABLE "MSSQL"."PRICINGFIELDTYPE" 
   (	"PRICINGFIELDTYPEID" NUMBER NOT NULL ENABLE, 
	"PRICINGFIELDTYPEDESC" VARCHAR2(80) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(60), 
	"EXAMPLE" VARCHAR2(250), 
	 CONSTRAINT "PK_PRICINGFIELDTYPE" PRIMARY KEY ("PRICINGFIELDTYPEID")
  USING INDEX PCTFREE 3 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 131072 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 