
  CREATE TABLE "MSSQL"."PRICINGOPTION" 
   (	"PRICINGOPTIONID" NUMBER NOT NULL ENABLE, 
	"OPTIONID" NUMBER NOT NULL ENABLE, 
	"PRICINGGROUPID" NUMBER NOT NULL ENABLE, 
	"PRECONDITION" VARCHAR2(219), 
	"PREVALUE" VARCHAR2(200) NOT NULL ENABLE, 
	"POSTCONDITION" VARCHAR2(200), 
	"POSTVALUE" VARCHAR2(200), 
	"PRECEDENCE" NUMBER, 
	"ORDERINDEX" NUMBER, 
	"FIELDTYPEID" NUMBER, 
	"REC_CREATE_DATE" DATE NOT NULL ENABLE, 
	"REC_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"UPDATED_BY" VARCHAR2(20), 
	 CONSTRAINT "PK_PRICINGOPTION" PRIMARY KEY ("PRICINGOPTIONID")
  USING INDEX PCTFREE 3 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 131072 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 