
  CREATE TABLE "MSSQL"."PRICINGOPTIONEXCEPT_PARENT" 
   (	"EXCEPTID" NUMBER NOT NULL ENABLE, 
	"OPTIONID" NUMBER NOT NULL ENABLE, 
	"PRECONDITION" VARCHAR2(219), 
	"PREVALUE" VARCHAR2(200) NOT NULL ENABLE, 
	"ORDERINDEX" NUMBER, 
	"FIELDTYPEID" NUMBER, 
	"REC_CREATE_DATE" DATE NOT NULL ENABLE, 
	"REC_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"UPDATED_BY" VARCHAR2(20), 
	"EXCEPTDESC" VARCHAR2(500), 
	 CONSTRAINT "OPTIONEXCEPT_PARENT_PK" PRIMARY KEY ("EXCEPTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "PRICINGOPTIONEXCEPT_PAREN_FK1" FOREIGN KEY ("EXCEPTID")
	  REFERENCES "MSSQL"."OPTIONTITLE" ("OPTIONTITLEID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MSSQL" 