
  CREATE TABLE "MSSQL"."OPTION_GLASS_LOWES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TINT" VARCHAR2(100), 
	"TINT_PRICE" NUMBER, 
	"TINT_PRICE_TYPE" VARCHAR2(20), 
	"ENERGY" VARCHAR2(100), 
	"ENERGY_PRICE" NUMBER, 
	"ENERGY_PRICE_TYPE" VARCHAR2(20), 
	"SAFETY" VARCHAR2(100), 
	"SAFETY_PRICE" NUMBER, 
	"SAFETY_PRICE_TYPE" VARCHAR2(20), 
	"PANE_TYPE" VARCHAR2(50), 
	"SERIES" VARCHAR2(200) DEFAULT 'ALL', 
	"STYLE" VARCHAR2(200) DEFAULT 'ALL', 
	"SHAPE" VARCHAR2(20) DEFAULT 'ALL', 
	"NFRC" NUMBER DEFAULT 0, 
	"CATEGORY" VARCHAR2(100) DEFAULT 'ALL', 
	"WIDTHES" NUMBER DEFAULT 0, 
	 CONSTRAINT "OPTION_GLASS_LOWES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 