
  CREATE TABLE "MSSQL"."OPTION_COTTAGEORIEL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(200) NOT NULL ENABLE, 
	"CLMR" NUMBER DEFAULT 0, 
	"CONSTRUCTIONCODE" VARCHAR2(20), 
	"PRICE" NUMBER, 
	"PRICE_TYPE" VARCHAR2(20) DEFAULT 'FIXED', 
	"PRICE_MUL" VARCHAR2(20) DEFAULT '1', 
	 CONSTRAINT "OPTION_COTTAGEORIEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "OPTION_COTTAGEORIEL_FK1" FOREIGN KEY ("PRICE_TYPE")
	  REFERENCES "MSSQL"."NEW_PRICINGTYPE" ("PRICECODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 