
  CREATE TABLE "MSSQL"."OPTION_SCREENMESHBU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SCREENMESH" VARCHAR2(200), 
	"PRICE" NUMBER, 
	"PRICE_TYPE" VARCHAR2(20), 
	"EFFECTIVEUNIT" NUMBER, 
	"SECTIONS" NUMBER, 
	"CONSTRUCTIONCODE" VARCHAR2(20), 
	"SERIES" VARCHAR2(200), 
	"STYLE" VARCHAR2(200), 
	"PRICEMUL" VARCHAR2(20), 
	"SCREENTYPE" VARCHAR2(200), 
	"PART" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 