
  CREATE TABLE "MSSQL"."PRICINGCUSTOM" 
   (	"STYLE" VARCHAR2(20), 
	"MODEL" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	"VALUE" VARCHAR2(20), 
	"LITES" NUMBER, 
	"BENT" NUMBER, 
	"PRICE" NUMBER, 
	"SHAPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 