
  CREATE TABLE "MSSQL"."OPTION_COLOR_LOWES" 
   (	"COLORID" NUMBER NOT NULL ENABLE, 
	"COLOR" VARCHAR2(200), 
	"PRICE" NUMBER, 
	"PRICETYPE" VARCHAR2(20), 
	"STYLE" VARCHAR2(20) DEFAULT 'ALL', 
	"MULLEDUNITS" NUMBER DEFAULT 1, 
	"PRICEMUL" VARCHAR2(20) DEFAULT '1', 
	"SECTIONS" NUMBER DEFAULT 1, 
	 CONSTRAINT "OPTION_COLOR_LOWES_PK" PRIMARY KEY ("COLORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 