
  CREATE TABLE "MSSQL"."OPTION_SCREENMESH_LOWES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SCREENMESH" VARCHAR2(200), 
	"PRICE" NUMBER, 
	"PRICE_TYPE" VARCHAR2(20), 
	"SECTIONS" NUMBER DEFAULT 1, 
	"CONSTRUCTIONCODE" VARCHAR2(20) DEFAULT '''R'',''N''', 
	"SERIES" VARCHAR2(200) DEFAULT 'ALL', 
	"STYLE" VARCHAR2(200) DEFAULT 'ALL', 
	"PRICEMUL" VARCHAR2(20) DEFAULT '1', 
	"SCREENTYPE" VARCHAR2(200) DEFAULT 'ALL', 
	"PART" NUMBER DEFAULT 0, 
	 CONSTRAINT "OPTION_SCREENMESH_LOWES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 