
  CREATE TABLE "MSSQL"."OPTION_GRIDBU" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20), 
	"PATTERN" VARCHAR2(500), 
	"GRIDSTYLE" VARCHAR2(200), 
	"CONSTRUCTION" VARCHAR2(20), 
	"PRICE" NUMBER, 
	"PRICETYPE" VARCHAR2(20), 
	"PRICEMUL" VARCHAR2(100), 
	"STYLE" VARCHAR2(500), 
	"GRIDCOLOROUT" VARCHAR2(200), 
	"GRIDPLACEMENT" VARCHAR2(200), 
	"SHAPES" NUMBER, 
	"SAFETY" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 