
  CREATE TABLE "MSSQL"."NEW_PRICINGSIZE_LOWES" 
   (	"SIZEID" NUMBER NOT NULL ENABLE, 
	"SERIES" VARCHAR2(200), 
	"MODEL" VARCHAR2(200), 
	"STYLE" VARCHAR2(200), 
	"WIDTH" NUMBER, 
	"HEIGHT" NUMBER, 
	"UI" NUMBER, 
	"UI_PRICETYPE" VARCHAR2(20), 
	"CLEAR" NUMBER, 
	"CLEAR_PRICETYPE" VARCHAR2(20), 
	"WITHGRID" NUMBER, 
	"WITHGRID_PRICETYPE" VARCHAR2(20), 
	"SCREEN_DEDUCT" NUMBER, 
	"SCREEN_DEDUCT_PRICETYPE" VARCHAR2(20), 
	"LOWERUI" NUMBER, 
	"UPPERUI" NUMBER, 
	"BRACKETPRICE" NUMBER, 
	"MAXUI" NUMBER, 
	"MAXUIPRICE" NUMBER, 
	"MAXPERUI" NUMBER, 
	"CLEAR_MINUI" NUMBER, 
	"WITHGRID_MINUI" NUMBER, 
	"TRIPLEEYEBROW" VARCHAR2(20), 
	"WIDTH_LOWER" NUMBER, 
	"WIDTH_UPPER" NUMBER, 
	"HEIGHT_LOWER" NUMBER, 
	"HEIGHT_UPPER" NUMBER, 
	"BB_PRICE" NUMBER, 
	"SECTIONS" NUMBER, 
	"BB_PRICE_TYPE" VARCHAR2(20), 
	 CONSTRAINT "NEW_PRICINGSIZE_LOWES_PK" PRIMARY KEY ("SIZEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 