
  CREATE TABLE "MSSQL"."NEW_PRICEMULTIPLIER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APPLYON" VARCHAR2(50), 
	"EFFECTIVEUNIT" VARCHAR2(20) DEFAULT 'NO', 
	"SECTIONS" VARCHAR2(20) DEFAULT 'NO', 
	"STYLE" VARCHAR2(200) DEFAULT '-', 
	"SERIES" VARCHAR2(200) DEFAULT '-', 
	"EXCEPTVALUES" VARCHAR2(200) DEFAULT '-', 
	"LITES" VARCHAR2(20) DEFAULT 'NO', 
	"MULTVALUE" VARCHAR2(100) DEFAULT '1', 
	"CONSTRUCTION" VARCHAR2(20) DEFAULT '''R'',''N''', 
	"GRIDPLACEMENT" VARCHAR2(20) DEFAULT '''0''', 
	 CONSTRAINT "NEW_PRICEMULTIPLIER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 