
  CREATE TABLE "MSSQL"."OPTION_FOAMWRAP" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TYPE" NUMBER, 
	"PRICE" NUMBER, 
	"PRICE_TYPE" VARCHAR2(20), 
	"PRICEMUL" VARCHAR2(20) DEFAULT '1', 
	"FOAMVALUE" VARCHAR2(200), 
	"SERIES" VARCHAR2(200) DEFAULT 'ALL', 
	"STYLE" VARCHAR2(200) DEFAULT 'ALL', 
	 CONSTRAINT "OPTION_FOAMWRAP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "OPTION_FOAMWRAP_FK1" FOREIGN KEY ("PRICE_TYPE")
	  REFERENCES "MSSQL"."NEW_PRICINGTYPE" ("PRICECODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 