
  CREATE TABLE "MSSQL"."OPTION_SCREEN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SCREEN" VARCHAR2(200), 
	"PRICE" NUMBER, 
	"PRICE_TYPE" VARCHAR2(20), 
	"SECTIONS" NUMBER DEFAULT 1, 
	"CONSTRUCTIONCODE" VARCHAR2(20) DEFAULT '''R'',''N''', 
	"SERIES" VARCHAR2(200) DEFAULT 'ALL', 
	"STYLE" VARCHAR2(500) DEFAULT 'ALL', 
	"PRICEMUL" VARCHAR2(20) DEFAULT 1, 
	"STDSIZE" VARCHAR2(20) DEFAULT '0,1', 
	"PARTS" NUMBER DEFAULT 0, 
	 CONSTRAINT "OPTION_SCREEN_SEAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL"  ENABLE, 
	 CONSTRAINT "OPTION_SCREEN_FK1" FOREIGN KEY ("PRICE_TYPE")
	  REFERENCES "MSSQL"."NEW_PRICINGTYPE" ("PRICECODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MSSQL" 