insert into OPTION_COTTAGEORIEL (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (1, '''ORIEL'',''COTTAGE''', 0, 'R', 36, 'FIXED', '1')
insert into OPTION_COTTAGEORIEL (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (2, '''ORIEL'',''COTTAGE''', 0, 'N', 15, 'FIXED', 'EFFECTIVEUNIT')
insert into OPTION_COTTAGEORIEL (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (3, '''ORIEL'',''COTTAGE''', 1, 'R', 72, 'FIXED', '1')
