insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('ATRIUMPRICE', 'lv_atriumprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('BASE', 'lv_baseprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('BREATHER TUBE', 'lv_breathertubeprice', 'lv_breathertube')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('COLOR', 'lv_colorprice', 'lv_framecolorin')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('COTTAGE/ORIEL', 'lv_cottageorielprice', 'lv_cottageoriel')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('DRYWALL', 'lv_drywallprice', 'lv_style')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('ENERGY', 'lv_energyprice', 'lv_energy')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('FINAL', 'lv_finalprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('FIXED SCREEN', 'lv_screenprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('FOAMWRAP', 'lv_foamwrapprice', 'lv_foamwrap')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GLASS', 'lv_glassprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID', 'lv_gridprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID COLOR', NULL, 'lv_gridcolorout')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID COLOR UPCHARGE', 'lv_gridcolorprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID PATTERN', NULL, 'lv_gridpattern')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID STYLE', NULL, 'lv_gridstyle')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID TSO ONLY', 'lv_gridpatternprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('GRID TYPE', NULL, 'lv_gridtype')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('HARDWARE', 'lv_hardwareprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('HARDWARE ACCESSORY', 'lv_hardwareaccessoryprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('HARDWARE COLOR/TYPE', 'lv_hardwaretype_colorprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('HARDWARE EGRESS', 'lv_hardwareegressprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('HEIGHT ES', NULL, 'lv_heightes')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('INFO', 'lv_info', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('LOCKS', 'lv_lockprice', 'lv_hardwaretype')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('MULLED UNITS', NULL, 'lv_mulledunits')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SAFETY', 'lv_safetyprice', 'lv_safety')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SASH ACCESSORY', 'lv_sashaccessoryprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SCREEN', 'lv_screenprice', 'lv_screentype')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SCREENMESH', 'lv_screenmeshprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SEAT', 'lv_seatprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SHAPES', NULL, 'lv_isshape')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SIMULATED MEETING RAIL', 'lv_smrprice', NULL)
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('STD SIZE', NULL, 'lv_stdsize')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('SUPER SPACER', 'lv_superspacerprice', 'lv_spacertype')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('TINT', 'lv_tintprice', 'lv_tintin')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('WIDTH ES', NULL, 'lv_widthes')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('WOOD/MULL', 'lv_wood_mullprice', 'lv_mulltype/lv_woodsurround')
insert into NEW_VARIABLEMAP (NAME,PRICEVARIABLE,INFOVARIABLE) values  ('WOOD/MULL CUSTOM SIZE', 'lv_woodcustomaddon', NULL)
