insert into OPTION_COTTAGEORIEL_LOWES (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (1, '''ORIEL'',''COTTAGE''', 0, 'R', 24, 'FIXED', '1')
insert into OPTION_COTTAGEORIEL_LOWES (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (2, '''ORIEL'',''COTTAGE''', 0, 'N', 10, 'FIXED', 'EFFECTIVEUNIT')
insert into OPTION_COTTAGEORIEL_LOWES (ID,TYPE,CLMR,CONSTRUCTIONCODE,PRICE,PRICE_TYPE,PRICE_MUL) values  (3, '''ORIEL'',''COTTAGE''', 1, 'R', 48, 'FIXED', '1')
