
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_EXCEPTIONDESC_TRG4" 
BEFORE INSERT ON NEW_EXCEPTIONDESC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.APPLYON IS NULL THEN
      SELECT NEW_EXCEPTIONDESC_SEQ.NEXTVAL INTO :NEW.APPLYON FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

