
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_WOOD_MULL_TRG" 
BEFORE INSERT ON OPTION_WOOD_MULL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_MULL_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

