
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_EXCEPTIONS_BASE_TRG2" 
BEFORE INSERT ON NEW_EXCEPTIONS_BASE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EX_SIZEID IS NULL THEN
      SELECT NEW_EXCEPTIONS_BASE_SEQ.NEXTVAL INTO :NEW.EX_SIZEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

