
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_COLOR_TRG1" 
BEFORE INSERT ON OPTION_COLOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COLORID IS NULL THEN
      SELECT OPTION_COLOR_SEQ1.NEXTVAL INTO :NEW.COLORID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

