
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."PRICING_DESC_MAP_TRG1" 
BEFORE INSERT ON PRICING_DESC_MAP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRICING_DESC_MAP_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

