
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICENEXCEPTLOG_TRG3" 
BEFORE INSERT ON NEW_PRICENEXCEPTLOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NEW_PRICENEXCEPTLOG_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

