
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICELOG_TRG2" 
BEFORE INSERT ON NEW_PRICELOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOGID IS NULL THEN
      SELECT NEW_PRICELOG_SEQ1.NEXTVAL INTO :NEW.LOGID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

