
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_GLASS_ALUMINUM_LOWES_T" 
BEFORE INSERT ON OPTION_GLASS_ALUMINUM_LOWES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_GLASS_ALUMINUM_LOWES_S.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

