
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_OTHERS_TRG2" 
BEFORE INSERT ON OPTION_OTHERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_OTHERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

