
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_COTTAGEORIEL_TRG" 
BEFORE INSERT ON OPTION_COTTAGEORIEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_COTTAGEORIEL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

