
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_FOAMWRAP_LOWES_TRG" 
BEFORE INSERT ON OPTION_FOAMWRAP_LOWES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.STYLE IS NULL THEN
      SELECT OPTION_FOAMWRAP_LOWES_SEQ.NEXTVAL INTO :NEW.STYLE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

