
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICINGSIZE_LOWES_TRG" 
BEFORE INSERT ON NEW_PRICINGSIZE_LOWES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SIZEID IS NULL THEN
      SELECT NEW_PRICINGSIZE_LOWES_SEQ.NEXTVAL INTO :NEW.SIZEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

