
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_COTTAGEORIEL_LOWES_TRG1" 
BEFORE INSERT ON OPTION_COTTAGEORIEL_LOWES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PRICE_MUL IS NULL THEN
      SELECT OPTION_COTTAGEORIEL_LOWES_SEQ.NEXTVAL INTO :NEW.PRICE_MUL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

