
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_GRID_TRG7" 
BEFORE INSERT ON OPTION_GRID 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_GRID_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

