
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_GLASS_ALUMINUM_TRG" 
BEFORE INSERT ON OPTION_GLASS_ALUMINUM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_GLASS_ALUMINUM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

