
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICINGSIZE_TRG1" 
BEFORE INSERT ON NEW_PRICINGSIZE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SIZEID IS NULL THEN
      SELECT NEW_PRICINGSIZE_SEQ1.NEXTVAL INTO :NEW.SIZEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

