
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICEMULTIPLIER_TRG4" 
BEFORE INSERT ON NEW_PRICEMULTIPLIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NEW_PRICEMULTIPLIER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

