
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_COLOR_LOWES_TRG" 
BEFORE INSERT ON OPTION_COLOR_LOWES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COLORID IS NULL THEN
      SELECT OPTION_COLOR_LOWES_SEQ.NEXTVAL INTO :NEW.COLORID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

