
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICINGSIZEMAP_TRG" 
BEFORE INSERT ON NEW_PRICINGSIZEMAP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MAPID IS NULL THEN
      SELECT NEW_PRICINGSIZEMAP_SEQ.NEXTVAL INTO :NEW.MAPID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

