
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."STYLE_DRYWALL_TRG" 
BEFORE INSERT ON OPTION_DRYWALL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STYLE_DRYWALL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

