
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."OPTION_HARDWARE_TRG2" 
BEFORE INSERT ON OPTION_HARDWARE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OPTION_HARDWARE_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

