
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICELOGHISTORY_TRG" 
BEFORE INSERT ON NEW_PRICELOGHISTORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOGID IS NULL THEN
      SELECT NEW_PRICELOGHISTORY_SEQ.NEXTVAL INTO :NEW.LOGID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

