
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."NEW_PRICING_CONFIG_TRG1" 
BEFORE INSERT ON NEW_PRICING_CONFIG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT NEW_PRICING_CONFIG_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

