
  CREATE OR REPLACE EDITIONABLE TRIGGER "MSSQL"."BI_PRICING_PRECONDTION_TRG" 
BEFORE INSERT ON PRICING_PRECONDITION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRICING_PRECONDTION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

